"""initial schema

Revision ID: 432a7545f047
Revises: 
Create Date: 2026-07-24 08:20:41.067193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '432a7545f047'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_filename', sa.String(length=1000), nullable=False),
    sa.Column('mime', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'READY', 'FAILED', name='document_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_blocks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('slide_no', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('provenance', sa.Enum('VERBATIM', 'OCR', 'MODEL_GENERATED', name='block_provenance', native_enum=False), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('producer', sa.String(length=255), nullable=True),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_blocks_document_slide_order', 'document_blocks', ['document_id', 'slide_no', 'order_index'], unique=False)
    op.create_table('learning_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'ARCHIVED', name='plan_status', native_enum=False), nullable=False),
    sa.Column('builder_prompt_version', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version', name='uq_learning_plans_document_version')
    )
    op.create_table('learning_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('slide_ids', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['learning_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_objectives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('low_confidence', sa.Boolean(), nullable=False),
    sa.Column('prerequisite_objective_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['learning_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objective_expected_ideas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('objective_id', sa.UUID(), nullable=False),
    sa.Column('idea', sa.Text(), nullable=False),
    sa.Column('block_id', sa.String(length=64), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.CheckConstraint('char_end > char_start', name='ck_expected_idea_span_nonempty'),
    sa.ForeignKeyConstraint(['block_id'], ['document_blocks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['objective_id'], ['learning_objectives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objective_misconceptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('objective_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['objective_id'], ['learning_objectives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('objective_id', 'code', name='uq_objective_misconceptions_objective_code')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ABANDONED', name='session_status', native_enum=False), nullable=False),
    sa.Column('current_objective_id', sa.UUID(), nullable=True),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['current_objective_id'], ['learning_objectives.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_id'], ['learning_plans.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_objective_states',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('objective_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('UNSEEN', 'PROBING', 'PARTIAL', 'MISCONCEPTION', 'CONFUSED', 'RESOLVED', 'DEFERRED', 'SKIPPED', name='objective_status', native_enum=False), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('hint_level', sa.Integer(), nullable=False),
    sa.Column('deepen_count', sa.Integer(), nullable=False),
    sa.Column('prereq_revisits', sa.Integer(), nullable=False),
    sa.Column('met_count', sa.Integer(), nullable=False),
    sa.Column('active_misconception_id', sa.String(length=100), nullable=True),
    sa.Column('last_action', sa.Enum('PROBE', 'HINT', 'REPHRASE', 'BRIDGE', 'RETEACH', 'CHECK_AGAIN', 'DEEPEN', 'REVISIT_PREREQ', 'ADVANCE', 'DEFER', 'ANSWER_QUESTION', 'REDIRECT', name='pedagogical_action', native_enum=False), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['objective_id'], ['learning_objectives.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'objective_id')
    )
    op.create_table('session_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('resolved', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('deferred', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('misconceptions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effective_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('turns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('student_message', sa.Text(), nullable=False),
    sa.Column('intent', sa.Enum('ANSWER', 'QUESTION', 'META', 'OFF_TASK', name='turn_intent', native_enum=False), nullable=True),
    sa.Column('action', sa.Enum('PROBE', 'HINT', 'REPHRASE', 'BRIDGE', 'RETEACH', 'CHECK_AGAIN', 'DEEPEN', 'REVISIT_PREREQ', 'ADVANCE', 'DEFER', 'ANSWER_QUESTION', 'REDIRECT', name='pedagogical_action', native_enum=False), nullable=True),
    sa.Column('tutor_message', sa.Text(), nullable=True),
    sa.Column('objective_id', sa.UUID(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['objective_id'], ['learning_objectives.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_turns_session_index', 'turns', ['session_id', 'index'], unique=False)
    op.create_table('llm_calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('turn_id', sa.UUID(), nullable=True),
    sa.Column('purpose', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('prompt_id', sa.String(length=200), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turn_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('turn_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_turn_events_session_created', 'turn_events', ['session_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_turn_events_session_created', table_name='turn_events')
    op.drop_table('turn_events')
    op.drop_table('llm_calls')
    op.drop_index('ix_turns_session_index', table_name='turns')
    op.drop_table('turns')
    op.drop_table('session_reports')
    op.drop_table('session_objective_states')
    op.drop_table('sessions')
    op.drop_table('objective_misconceptions')
    op.drop_table('objective_expected_ideas')
    op.drop_table('learning_objectives')
    op.drop_table('learning_units')
    op.drop_table('learning_plans')
    op.drop_index('ix_document_blocks_document_slide_order', table_name='document_blocks')
    op.drop_table('document_blocks')
    op.drop_table('documents')
    # ### end Alembic commands ###
