"""documents content_hash storage_uri error

Revision ID: 5a533576cf46
Revises: 432a7545f047
Create Date: 2026-07-24 08:46:30.263970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a533576cf46'
down_revision: Union[str, Sequence[str], None] = '432a7545f047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content_hash', sa.String(length=64), nullable=False))
    op.add_column('documents', sa.Column('storage_uri', sa.Text(), nullable=False))
    op.add_column('documents', sa.Column('error', sa.Text(), nullable=True))
    op.create_unique_constraint('uq_documents_content_hash', 'documents', ['content_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_documents_content_hash', 'documents', type_='unique')
    op.drop_column('documents', 'error')
    op.drop_column('documents', 'storage_uri')
    op.drop_column('documents', 'content_hash')
    # ### end Alembic commands ###
