""""plan review: reviewed flag and plan_edits audit table

Revision ID: cf762c763b6f
Revises: 5a533576cf46
Create Date: 2026-07-24 16:58:13.177261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf762c763b6f'
down_revision: Union[str, Sequence[str], None] = '5a533576cf46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_edits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('objective_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('update', 'delete', 'approve', name='plan_edit_action', native_enum=False), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['learning_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plan_edits_plan_created', 'plan_edits', ['plan_id', 'created_at'], unique=False)
    # server_default backfills the 41 pre-existing learning_objectives rows
    # (the networking_101 demo plan built while working on Module 2) so the
    # NOT NULL add_column doesn't fail against real data.
    op.add_column(
        'learning_objectives',
        sa.Column('reviewed', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('learning_objectives', 'reviewed', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_objectives', 'reviewed')
    op.drop_index('ix_plan_edits_plan_created', table_name='plan_edits')
    op.drop_table('plan_edits')
    # ### end Alembic commands ###
