"""Regression suite for the provenance-tagged Block extraction contract
(see CLAUDE.md and docs/ARCHITECTURE_REVIEW_AND_ROADMAP.md §1.1 / §2.6).

Fixture decks live under tests/fixtures/decks/<name>/deck.pdf and are
synthetic (generated by tests/fixtures/generate_decks.py) since real lecture
decks are not checked into the repo. Golden output lives alongside each deck
as expected_blocks.json (tests/fixtures/generate_expected_blocks.py).
"""

import json
import random
from pathlib import Path

import pytest

from slidevision.extraction.blocks import (
    block_from_visual_description,
    build_document_blocks,
    make_block_id,
)
from slidevision.extraction.models import Block
from slidevision.extraction.utils import hash_file

DECKS_DIR = Path(__file__).parent.parent / "fixtures" / "decks"
DECK_NAMES = sorted(p.name for p in DECKS_DIR.iterdir() if (p / "deck.pdf").exists())

VALID_PROVENANCE = {"verbatim", "ocr", "model_generated"}


def _build_blocks_for_deck(deck_name: str) -> tuple[str, list[Block], list[str]]:
    deck_path = DECKS_DIR / deck_name / "deck.pdf"
    document_id = hash_file(deck_path)
    warnings: list[str] = []
    blocks = build_document_blocks(deck_path, document_id=document_id, force_ocr=False, warnings=warnings)
    return document_id, blocks, warnings


def _load_golden(deck_name: str) -> dict:
    golden_path = DECKS_DIR / deck_name / "expected_blocks.json"
    return json.loads(golden_path.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def deck_names() -> list[str]:
    assert len(DECK_NAMES) >= 5, "expected at least 5 fixture decks (see tests/fixtures/generate_decks.py)"
    return DECK_NAMES


@pytest.mark.parametrize("deck_name", DECK_NAMES)
def test_golden_regression(deck_name: str) -> None:
    """Freshly extracted blocks must match the checked-in golden exactly."""
    document_id, blocks, warnings = _build_blocks_for_deck(deck_name)
    golden = _load_golden(deck_name)

    assert document_id == golden["documentId"]
    assert warnings == golden["warnings"]
    assert [block.model_dump() for block in blocks] == golden["blocks"]


@pytest.mark.parametrize("deck_name", DECK_NAMES)
def test_no_null_provenance(deck_name: str) -> None:
    _, blocks, _ = _build_blocks_for_deck(deck_name)
    assert blocks, f"{deck_name} produced no blocks at all"
    for block in blocks:
        assert block.provenance is not None
        assert block.provenance in VALID_PROVENANCE


@pytest.mark.parametrize("deck_name", DECK_NAMES)
def test_block_ids_deterministic_across_reruns(deck_name: str) -> None:
    """Re-running extraction on the same file must produce identical block_ids."""
    document_id_1, blocks_1, _ = _build_blocks_for_deck(deck_name)
    document_id_2, blocks_2, _ = _build_blocks_for_deck(deck_name)

    assert document_id_1 == document_id_2
    assert [b.block_id for b in blocks_1] == [b.block_id for b in blocks_2]


def test_document_id_is_stable_hash_of_file_bytes(deck_names: list[str]) -> None:
    """document_id must depend only on the file's bytes, not on when/how many
    times extraction runs (this is what makes block_id re-runs stable)."""
    for deck_name in deck_names:
        deck_path = DECKS_DIR / deck_name / "deck.pdf"
        assert hash_file(deck_path) == hash_file(deck_path)


def test_make_block_id_is_pure_function_of_its_inputs() -> None:
    assert make_block_id("doc-a", 3, 2) == make_block_id("doc-a", 3, 2)
    assert make_block_id("doc-a", 3, 2) != make_block_id("doc-b", 3, 2)
    assert make_block_id("doc-a", 3, 2) != make_block_id("doc-a", 4, 2)
    assert make_block_id("doc-a", 3, 2) != make_block_id("doc-a", 3, 3)


def test_scanned_deck_produces_only_ocr_blocks_with_confidence() -> None:
    _, blocks, _ = _build_blocks_for_deck("scanned_ocr")
    assert blocks
    for block in blocks:
        assert block.provenance == "ocr"
        assert block.ocr_confidence is not None
        assert 0.0 <= block.ocr_confidence <= 1.0
        assert block.producer is None


def test_text_heavy_deck_produces_only_verbatim_blocks() -> None:
    _, blocks, _ = _build_blocks_for_deck("text_heavy")
    assert blocks
    for block in blocks:
        assert block.provenance == "verbatim"
        assert block.ocr_confidence is None
        assert block.producer is None


def test_mixed_deck_has_both_verbatim_and_ocr_slides() -> None:
    """The mixed deck's third slide has no text layer (scanned), so the deck
    as a whole must span both provenance types across its slides."""
    _, blocks, _ = _build_blocks_for_deck("mixed")
    provenances_by_slide: dict[int, set[str]] = {}
    for block in blocks:
        provenances_by_slide.setdefault(block.slide_no, set()).add(block.provenance)

    assert provenances_by_slide[1] == {"verbatim"}
    assert provenances_by_slide[2] == {"verbatim"}
    assert provenances_by_slide[3] == {"ocr"}


@pytest.mark.parametrize("deck_name", DECK_NAMES)
def test_order_index_is_contiguous_per_slide(deck_name: str) -> None:
    _, blocks, _ = _build_blocks_for_deck(deck_name)
    by_slide: dict[int, list[int]] = {}
    for block in blocks:
        by_slide.setdefault(block.slide_no, []).append(block.order_index)

    for slide_no, order_indexes in by_slide.items():
        assert order_indexes == list(range(len(order_indexes))), (
            f"{deck_name} slide {slide_no} has non-contiguous order_index: {order_indexes}"
        )


def test_char_offsets_survive_json_roundtrip() -> None:
    """(block_id, char_start, char_end) anchors (added by later modules) only
    work if a block's `text` is unchanged by persistence. Simulates that
    round-trip: serialize every block to JSON, deserialize, and confirm an
    arbitrary substring slice is identical before and after."""
    random.seed(1234)  # deterministic sample across runs

    all_blocks: list[Block] = []
    for deck_name in DECK_NAMES:
        _, blocks, _ = _build_blocks_for_deck(deck_name)
        all_blocks.extend(blocks)

    candidates = [block for block in all_blocks if len(block.text) >= 2]
    assert len(candidates) >= 20, "need at least 20 non-trivial blocks across fixture decks to sample from"

    sample = random.sample(candidates, 20)

    for block in sample:
        serialized = block.model_dump_json()
        restored = Block.model_validate_json(serialized)

        char_start = random.randint(0, len(block.text) - 2)
        char_end = random.randint(char_start + 1, len(block.text))

        original_slice = block.text[char_start:char_end]
        restored_slice = restored.text[char_start:char_end]

        assert restored_slice == original_slice
        assert restored.text == block.text
        assert restored.block_id == block.block_id


def test_block_from_visual_description_tags_model_generated() -> None:
    description = {
        "markdownBlock": "### Visual Explanation\n\nA bar chart comparing throughput across three servers.",
        "model": "gemini-2.5-flash",
    }

    block = block_from_visual_description(description, document_id="doc-x", slide_no=4, order_index=2)

    assert block is not None
    assert block.provenance == "model_generated"
    assert block.producer == "gemini-2.5-flash"
    assert block.ocr_confidence is None
    assert block.bbox is None
    assert block.block_id == make_block_id("doc-x", 4, 2)
    assert block.text == description["markdownBlock"]


def test_block_from_visual_description_drops_errors_and_empty_output() -> None:
    assert block_from_visual_description({"error": "timeout"}, "doc-x", 1, 0) is None
    assert block_from_visual_description({"markdownBlock": ""}, "doc-x", 1, 0) is None
    assert block_from_visual_description({}, "doc-x", 1, 0) is None


def test_block_model_rejects_invalid_provenance() -> None:
    with pytest.raises(Exception):
        Block(
            block_id="b_x",
            document_id="doc-x",
            slide_no=1,
            order_index=0,
            text="hello",
            provenance="invented",  # type: ignore[arg-type]
        )
